### ISSUE TITLE
Instantclick does not keep webkit-scrollbar styles between loadings

### ISSUE THREAD

**Issue by julienduthoit** [dieulot/instantclick#138]
Hi,

I've tested InstantClick on some websites and it works great but recently I got this problem.
On a website, the scrollbar is styled with the ::-webkit-scrollbar attributes. But after a page loading, I can't retrieve this style, is there a way to keep this functionality?

Thanks for your help

**Comment by dieulot** [comment]
Ouch. I don't know any way to fix that.

Note to other people: What happens is that the scrollbar disappears on page change. You can try it out by adding this to tests/style.css:

```css
::-webkit-scrollbar {
	width: 15px;
	background: #ddd;
}

::-webkit-scrollbar-thumb {
	background: #777;
}
```

I tested with Chrome on Linux and Safari 10 on macOS, both have the problem.

The only way I see to fix this is to report those issues to Blink and WebKit so that it’s fixed in a later version of those browsers. I’ll do that later, unless somebody is motivated to do it in the meantime.
